config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root :to => 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true, length: { maximum: 35 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/post.rb
class Post < ApplicationRecord

    attachment :image
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :view_counts, dependent: :destroy

    validates :location, presence: true, length: { maximum: 15 }
    validates :text, presence: true, length: { maximum: 195 }
    validates :image, presence: true

    enum status: { published: 0, draft: 1 }
    
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :view_counts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :profile_image

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  validates :name, presence: true
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.page(params[:page]).reverse_order
    @posts = @posts.where('location LIKE ?', "%#{params[:search]}") if params[:search].present?
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
    unless ViewCount.find_by(user_id: current_user.id, post_id: @post.id)
      current_user.view_counts.create(post_id: @post.id)
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end
  
  private
  def post_params
    params.require(:post).permit(:user_id, :location, :text, :image, :status)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    def create
        @room = Room.create(user_id: current_user.id)
        @current_entry = Entry.create(:room_id => @room.id, :user_id => current_user.id)
        @another_entry = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
        redirect_to "/rooms/#{@room.id}"
    end

    def show
        @room = Room.find(params[:id])
        if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
            @messages = @room.messages
            @message = Message.new
            @entries = @room.entries
            @myUserId = current_user.id
        else
          redirect_back(fallback_location: root_path)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(5).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(8).reverse_order
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_index.html.erb
    <div class="row mt-3 mb-3 align-self-end">
      <%= form_with url: posts_path, method: :get, local: true do |f| %>
        <%= f.text_field :search %>
        <%= f.submit '検索する', name: nil %>
      <% end %>
    </div>
    <div class="row mt-5 index-left w-100">
      <% posts.each do |post| %>
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do %>
            <p class="caption"><%= post.user.name %></p>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
            <p class="caption"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p> 
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate posts %>

app/views/posts/confirm.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">下書き一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-normal mt-5 mb-5">投稿編集</h1>
    </div>
    <% if @post.errors.any? %>
      <div class="card text-center text-white bg-danger mb-3">
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <div class="row">
      <%= form_with model: @post, local:true do |f| %>
        <div class="form-group mb-3">
          <label class="form-label">旅行先</label>
          <%= f.text_field :location, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">感想</label>
          <%=f.text_area :text, rows: 10, class: "form-control" %>
        </div>
        <div class="form-group mb-4">
          <label class="form-label">画像</label><br>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
        </div>
        <%= f.submit '保存する', class: "btn btn-success" %><br>
        <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿一覧</h1>
    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do %>
            <p class="caption"><%= post.user.name %></p>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
            <p class="caption"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p> 
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="cover-new">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">新規投稿ページ</h1>
    </div>
    <% if @post.errors.any? %>
      <div class="card text-center text-white bg-danger mt-3">
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <div class="row mt-5">
      <%= form_with model: @post, local:true do |f| %>
        <div class="form-group mb-3">
          <label class="form-label">【旅行先】</label>
          <%= f.text_field :location, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">【感想】</label>
          <%=f.text_area :text, rows: 10, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">【画像】</label><br>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
        </div>
        <%= f.submit '投稿する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5 mb-5">
      <h1 class="font-weight-normal">旅行投稿詳細</h1>
    </div>
    <% if @comment.errors.any? %>
      <div class="card text-center text-white bg-danger mt-3">
        <%= @comment.errors.count %>件のエラーが発生しました
        <% @comment.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <div class="container d-flex mt-5">
      <div class="d-block">
        <p class="caption"><%= @post.user.name %></p>
        <%= attachment_image_tag @post, :image, format: 'jpeg', size: "450x350" %><br>
        <p class="caption"><%= @post.location %>
          <% if @post.favorited_by?(current_user) %>
            <%= link_to post_favorites_path(@post),  data: { turbo_method: :delete }, class: "favorite_btn" do %>
              ♥<%= @post.favorites.count %> いいね
            <% end %>
          <% else %>
            <%= link_to post_favorites_path(@post),  data: { turbo_method: :post }, class: "favorite_btn" do %>
              ♡<%= @post.favorites.count %> いいね
            <% end %>
          <% end %>
            <td>閲覧数: <%= @post.view_counts.count %></td>
        </p>     
        <h2>感想</h2>
        <p id="text"><%= @post.text %></p>
        <% if @post.user == current_user %>
            <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
            <%= link_to '削除する', post_path(@post.id),  data: { turbo_method: :delete, turbo_confirm:  "本当に削除しますか？"}, class: "btn btn-danger" %><br>
        <% end %>
        <%= link_to '投稿一覧へ', posts_path, class: "btn btn-dark mt-3" %>
      </div>
      <div class="comments ml-5 mt-5">
        <%= form_with(model:[@post, @comment], local: true) do |f| %>
          <%= f.text_area :comment, :size=>"60x3",placeholder: "コメント" %>
          <%= f.submit "送信", class: "btn btn-success mb-4" %>
        <% end %>

        <p>コメント件数：<%= @comments.count %></p>
        <% @comments.each do |comment| %>
          <div class="comments-index mb-2">
            <%= comment.user.name %>
            <%= comment.created_at.strftime('%Y/%m/%d') %><br>
            <div class="d-flex">
              <%= comment.comment %>
              <% if comment.user == current_user %>
                <div class="comment-delete">
                  <%= link_to "削除する", post_comment_path(comment.post, comment),  data: { turbo_method: :delete }, class: "btn-sm btn-danger" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="chat-container">

  <div class="chat-wrapper">

  <% @entries.each do |e| %>
    <% if @myUserId != e.user.id %>
      <h2 class="chat-title"><%= e.user.name %>さんとのトークルーム</h2>
    <% end %>
  <% end %>

  <div class="chat-messages">
    <% if @messages.present? %>

      <% @messages.each do |m| %>
        <% if @myUserId == m.user.id %>
          <!-- 自分のメッセージ -->
          <div class="message message-own">
            <div class="message-content">
              <p><%= m.message %></p>
            </div>
          </div>
        <% else %>
          <!-- 相手のメッセージ -->
          <div class="message message-other">
            <div class="message-sender"><%= m.user.name %></div>
            <div class="message-content">
              <p><%= m.message %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="chat-form">
    <%= form_for @message do |f| %>
      <%= f.text_field :message, placeholder: "メッセージを入力して下さい", class: "chat-input" %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.submit "送信する", class: "chat-submit" %>
    <% end %>
  </div>

</div>



app/views/users/_index.html.erb
    <div class="row mt-5 w-50">
      <% users.each do |user| %>
        <div class="one-post card mt-3">
          <%= link_to user_path(user) do %>
            <div class="d-flex">
              <%= attachment_image_tag user, :profile_image, size: '50x50', fallback: "no_image.svg", class: "mt-3 profile-img" %>
              <p class="caption h4 mt-4"><%= user.name %></p>
            </div>
            <p class="caption h4"><%= user.name %></p>
            <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate users %>

app/views/users/edit.html.erb
<div class="cover-user-edit">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">プロフィール編集</h1>
    </div>
    <div class="row mt-5">
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <laabel class="form-label">名前</label>
          <%= f.text_field :name, autofocus: true, ide:"inputName", placeholder:"名前", class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">プロフィール画像</label><br>
          <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %><br>
          <%= f.file_field :profile_image %>
        </div>
        <div class="form-group">
          <label class="form-label">プロフィール</label>
          <%= f.text_field :profile, class: "form-control" %><br>
        </div>
        <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロワー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">ユーザー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <% if user_signed_in? && @user == current_user %>
        <h1 class="font-weight-normal">マイページ</h1>
      <% else %>
        <h1 class="font-weight-normal"><%= @user.name %>さんのページ</h1>
      <% end %>
    </div>
    <% if user_signed_in? && @user == current_user %>
      <p class="d-flex align-self-end">
        <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success" %>
      </p>
    <% end %>
    <% unless @user.id == current_user.id %>
  <% if (current_user.following? @user) && (@user.following? current_user)  %>
  <% if @is_room == true %>
    <p class="user-show-room"><a href="/rooms/<%= @room_id %>" class="btn btn-primary btn-lg">チャットを始める</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
    <% end %>
  <% end %>
  <% end %>
<% end %>

    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォロー外す', user_relationships_path(@user.id), data: { turbo_method: :delete }, class: "btn btn-danger" %>
        </p>
        <% else %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォローする', user_relationships_path(@user.id), data: { turbo_method: :post }, class:"btn btn-success" %> 
        </p>
      <% end %>
    <% end %> 
    <div class="d-flex w-100">
      <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %>
      <h4 class="ml-3 mb-3 card w-100 profile"><%= @user.profile %></h4>
    </div>    
    <div class="d-flex">
      <%= link_to follows_user_path(@user) do %>
        <h6>フォロー<%= @following_users.count %></h6>
      <% end %>
      <%= link_to followers_user_path(@user) do %>
        <h6>フォロワー<%= @follower_users.count %></h6>
      <% end %>
    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-3 mb-3">
          <%= link_to post_path(post) do %>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '200x133' %>
            <p class="caption mb-0"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>